#!/usr/bin/env bash
# Shebang kempbang
file="/etc/passwd"
IFS=":"
cat < "$file" | while IFS= read -r line
do
    read -r -a array <<< "$line"
    username="${array[0]}"
    group_id="${array[3]}"
    home_dir="${array[5]}"
    cmd="${array[6]}"
    pass="${array[1]}"
    user_info="${array[4]}"
    user_id="${array[2]}"
    echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $cmd. $user_id's place is protected by the passcode $pass, more info about the user here: $user_info"
done
