#!/usr/bin/env bash
# The clock in bash
min=0
hr=-1
while [ $min -le 779 ]
do
    ((dis = min % 60))
    if [ $dis -eq 0 ]
    then
        ((hr += 1))
        echo "Hour: $hr"
    else
        echo "$dis"
    fi
    ((min += 1))
done
