#!/usr/bin/env bash
# Configuration file fot the nginx

echo "Updating packages and installing requirements"

# Update package Manager
sudo apt update
sudo apt-get install -y nginx

# Install pip
sudo apt-get install -y python3-pip

# Install Flask, flask-cors, sqlalchemy Using pip
pip install flask
pip install flask_cors
pip install sqlalchemy

# Install net-tools
sudo apt-get install net-tools

# Install Gunicorn
sudo apt-get install -y gunicorn

# Remove all AirBNB repositories present
rm -rf AirBnB_clone_v*

# Clone All AirBnB repostories
git clone https://github.com/SamajesteDigho/AirBnB_clone_v2
git clone https://github.com/SamajesteDigho/AirBnB_clone_v3
git clone https://github.com/SamajesteDigho/AirBnB_clone_v4

# Move to the Airbnb v2
cd AirBnB_clone_v2

# Switch branch
git checkout app-server

# Define the path to the Nginx configuration file
NGINX_CONFIG="/etc/nginx/sites-enabled/default"

# Overwrite the NGINX configuration file with the provided config file
sudo tee "$NGINX_CONFIG" > /dev/null <<EOF
server {
    listen 80 default_server;

    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Server-By \$hostname;
    location /hbnb_static {
        alias /data/web_static/current;
    }
    location /static/ {
        alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/;
        try_files \$uri \$uri/ =404;
    }
    location / {
        proxy_pass http://0.0.0.0:5003;
    }
    location /airbnb-onepage {
        proxy_pass http://0.0.0.0:5000/airbnb-onepage;
    }
    location ~ ^/airbnb-dynamic/number_odd_or_even/([0-9]+)$ {
        proxy_pass http://0.0.0.0:5001/number_odd_or_even/\$1;
    }
    location /api/ {
        proxy_pass http://0.0.0.0:5002;
    }
    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}
EOF

# Restart Nginx to apply the changes
sudo systemctl restart nginx

echo "Nginx configuration has been successfully updated"

# Setup tmux session for task 4
cd /home/ubuntu/AirBnB_clone_v3
tmux new-session -d 'gunicorn --bind 0.0.0.0:5002 api.v1.app:app'

# Setup tmux session for task 5
cd /home/ubuntu/AirBnB_clone_v4
git checkout app-server

echo "Done !!!"
